# Generated by Django 2.0 on 2018-04-29 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Command Name')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConfigCommand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_command', models.CharField(max_length=500, verbose_name='Config Command')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nugget Name')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nugget Name')),
                ('total', models.CharField(max_length=100, verbose_name='Total')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.CharField(choices=[('1', 'PRECHECK'), ('2', 'POSTCHECK')], max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
            ],
        ),
        migrations.CreateModel(
            name='NuggetCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_name', models.CharField(max_length=100, verbose_name='Type Command')),
                ('command_output', models.CharField(max_length=5000, verbose_name='Command Output')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('command_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoicing.Meal')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoicing.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='NuggetText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_data', models.CharField(max_length=100, verbose_name='TEXT')),
                ('data_type', models.CharField(choices=[('1', 'TEXT'), ('2', 'IPV4'), ('3', 'IPV6'), ('4', 'Boolean'), ('5', 'Number')], max_length=10)),
                ('data_operator', models.CharField(choices=[('1', '>'), ('2', '<'), ('3', '<='), ('4', '>='), ('5', '!=')], max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('nugget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nugget_texts', to='invoicing.NuggetCheck')),
            ],
        ),
        migrations.AddField(
            model_name='configcommand',
            name='config_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoicing.Invoice'),
        ),
    ]
