# Generated by Django 2.0 on 2018-04-29 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configcommand',
            name='config_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoicing.Customer'),
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
