# Generated by Django 2.0 on 2018-04-30 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0002_auto_20180429_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nuggetcheck',
            name='command_check',
        ),
    ]
